name 'ls_user_mgmt_tool'
maintainer 'John Snow'
maintainer_email 'thelunaticscripter@outlook.com'
issues_url 'https://github.com/TheLunaticScripter/user_mgmt_tool'
source_url 'https://github.com/TheLunaticScripter/user_mgmt_tool'
version '1.2.4'
